# Generated by Django 6.0.2 on 2026-02-12 10:16

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('icon', models.CharField(default='📁', help_text='Emoji icon', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=portal.models.content_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('image', 'Image'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, editable=False)),
                ('duration', models.CharField(blank=True, help_text='e.g. 1h 23m', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('downloads', models.PositiveIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.category')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
