# Generated by Django 6.0.2 on 2026-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(default='Community CDN Node', max_length=100)),
                ('tagline', models.CharField(default='by Community Networks', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Replaces the emoji icon in the sidebar', null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Main brand color (buttons, links, active states)', max_length=7)),
                ('accent_color', models.CharField(default='#1d4ed8', help_text='Darker accent / hover color', max_length=7)),
                ('sidebar_color', models.CharField(default='#0c111d', help_text='Sidebar background color', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('📁', '📁 Folder'), ('📂', '📂 Open Folder'), ('🎬', '🎬 Movies / Video'), ('📺', '📺 TV Series'), ('🎵', '🎵 Music'), ('🎶', '🎶 Audio'), ('🎤', '🎤 Podcast'), ('📄', '📄 Documents'), ('📚', '📚 Books / Library'), ('📰', '📰 News'), ('🖼️', '🖼️ Images / Photos'), ('📷', '📷 Photography'), ('💾', '💾 Software'), ('🎮', '🎮 Games'), ('💻', '💻 Computer / Tech'), ('📱', '📱 Mobile Apps'), ('🌐', '🌐 Web / Internet'), ('📡', '📡 Network / CDN'), ('🔧', '🔧 Tools'), ('⚙️', '⚙️ Technical'), ('🎓', '🎓 Education'), ('🔬', '🔬 Science'), ('🏥', '🏥 Health'), ('🌍', '🌍 Geography'), ('✈️', '✈️ Travel'), ('🏠', '🏠 Home'), ('🍎', '🍎 Food'), ('🎨', '🎨 Art / Design'), ('🎭', '🎭 Drama / Theater'), ('🎯', '🎯 Sports')], default='📁', max_length=10),
        ),
    ]
