# Generated by Django 6.0.2 on 2026-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_sitesettings_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Announcement message or description')),
                ('announcement_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('promo', 'Promo / Ad')], default='info', max_length=10)),
                ('icon', models.CharField(default='📢', help_text='Emoji icon', max_length=10)),
                ('link', models.URLField(blank=True, help_text='Optional link (e.g., to a file, external page)')),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show this announcement on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date/time', null=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
