# Generated by Django 6.0.2 on 2026-02-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='media_image',
            field=models.ImageField(blank=True, help_text='Upload an image/poster for this announcement', null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL (YouTube, Vimeo, or direct MP4 link)'),
        ),
    ]
