# Generated by Django 6.0.2 on 2026-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_announcement_media_image_announcement_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_extract_colors',
            field=models.BooleanField(default=True, help_text='Automatically extract theme colors from the uploaded logo'),
        ),
    ]
